Repository BuildForSDGCohort2/team-185-frontend, pull requests merged in 2020-09, with the labels that each got.

#7 Staging
  .gitignore
  README.md
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.js
  src/components/Navigation/Header.js
  src/index.js
  src/store/reducers/authReducer.js
  src/store/store.js
Labels: Javascript, REACT, UI, enhancement, good first issue

#9 Pushing unstaged files
  README.md
  package.json
  src/App.css
  src/App.js
  src/index.js
Labels: Frontend, Javascript, Production, REACT, UI, enhancement

#10 ReadMe and Node Engine
  README.md
  package.json
Labels: :100: :muscle: Well Done!, :1st_place_medal: Congrats :clap:, Axios, Bootstrap!, Frontend, Javascript, REACT, Redux, enhancement

#16 Aligning/Justify Components
  src/components/ExpenseSummary.js
  src/components/IncomeSummary.js
Labels: Bootstrap!, Javascript
